title: My page testing 
author: jahid-ictian
email: 123email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  I am a undergrad student of ICT. I'm learning how to create  github pages.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
